// The "i" panel. Deliberate rule: never name the game's inspirations here.
import { closeInfo } from "../game/engine.js";

export default function InfoOverlay(){
  return (
    <div className="overlay">
      <div className="box panel">
        <h2>HOW THIS WORKS</h2>
        <div style={{fontSize:8,marginBottom:12,lineHeight:1.9}}>
          You're a lawyer at PARSON HENDERSON LLP. Case files land in your INBOX — read them carefully; the winning argument is usually hiding in the text.<br/><br/>
          Every option has success odds — how much of them you SEE depends on the difficulty you picked: a range on EASY, a wider one on MEDIUM and HARD, nothing at all on REALISTIC. The dice are always exact; only your information blurs. GREEN options never fail but drain your BOLDNESS. RED options are bluffs — their odds scale with Boldness, and failing them burns REPUTATION. Rare COVERT ACTIONS are different: the file must reveal the opportunity, then you execute it yourself. Picking a lock or isolating live circuits does not win the lawsuit — it earns evidence for the legal decision that follows. Fail noisily and one called coin decides whether you escape or get caught.<br/><br/>
          REPUTATION below 20: you're fired. One exception must be earned: if a fatal aggressive play began at BOLD 70+ after at least three landed bluffs and while your bluff record was still winning, FINAL WARNING fires automatically once per run. It restores REP to 28 but burns 15 BOLD; there is no second warning. INFLUENCE climbs the career ladder: Junior Associate to NAME PARTNER (that's the win). Low reputation also means less respect — risky plays get harder and your office gets sadder.<br/><br/>
          Solved work also earns XP. LEVEL is separate from your firm title: each level grants one permanent point for this career. SNEAKY makes lock windows wider, adds attempts at key ranks, and slows Power Cut circuits; ENDURANCE reduces positive fatigue earned from work. Your starting scenario gives its own innate strengths. Failed work still teaches something, but delegation teaches far less, deadlines teach nothing, and delayed cases grant XP only when the reply reveals the result.<br/><br/>
          The workday runs 09:00 to 17:00 and every piece of work COSTS HOURS — and careful lawyering is SLOW lawyering: safe plays take ×1.5 time, technical ×1.25; the bluff is the only fast move in the building. Technical wins build trust but pay less INFLUENCE; aggressive wins are the faster climb when your Boldness can carry them. Out of hours with files still burning? You may take at most TWO overtime blocks: +2 hours for +12 FATIGUE, then +2 for +18. Fatigue drags every risky play down (up to −25%); sleep clears it, leaving early clears more, and the EXPENSES panel sells at most two diminishing espressos per day. In THE FRAUD, reaching 80+ FATIGUE while working arms one identity-slip check at day end, based on the day's highest reached fatigue: 0.5% at 80–89, 1.5% at 90–94, 3% at 95–99 and 5% at 100. Coffee cannot erase an already reached peak. The random slip itself never ends the run. It opens a cover-up decision before ordinary morning consequences; failed answers raise visible SUSPICION and schedule escalating identity inquiries. Every stage has a guaranteed answer whose own cost is nonlethal, then the rest of that morning resumes normally. Bosses will interrupt your day with chores; refusing is noted, obeying is tiring. Colleagues you've truly earned (rel 40+) may open doors of their own. Cases have deadlines — miss one and it costs you. Court files show each judge's TEMPER, BY-THE-BOOK instinct and ETHICS. Judges keep your whole career record, but today's odds weigh only your last three appearances — the newest matters most, and changing your approach cools an old pattern. Repeated bluffs become familiar, recent technical wins build credibility, technical failures spend it, and repeat impropriety gets harder. Career totals, active recall and the exact live effect are printed before you choose.<br/><br/>
          Reputation decays a little every day. This firm forgets fast. Stay visible.<br/><br/>
          Every fifth day is FRIDAY: the partners review your week — influence gained, reputation kept, deadlines missed. A strong week earns a nod (+REP, +INFLUENCE); a weak one gets measured out loud (−REP). Meeting an Influence threshold makes you promotion-ready; titles normally change only after this review and at most one rank per week. A Senior Partner who keeps earning after the 100 INFLUENCE ceiling builds EXCEPTIONAL REVIEW momentum: 36 clipped points can bring the Name Partner vote forward on a later morning, after at least two days in rank, while REP is 30+ and the normal FIRM gate is met. Friday still takes priority. Friday also collects the CLIENT retainers. Clients are EARNED, never given: win loudly and prospects call, retiring partners hand you their accounts, dinner invitations appear. Lose loudly and clients quietly leave. The outside world — bankruptcies, poaching, scandals — occasionally takes a bite too.<br/><br/>
          Money is for spending: a TAILORED SUIT buys respect, MARV knows who your colleagues really are, and a DETECTIVE can tilt a single case file. Climbing the ladder raises the STAKES — wins pay more, failures cost much more.<br/><br/>
          Your run saves itself (except in IRONMAN — there, closing the game ends the career). ENDLESS keeps the clock running after you make Name Partner; DAILY deals everyone the same date-seeded run. Achievements live on the start screen.<br/><br/>
          The FIRM bar is the firm's health. In STANDARD, clients notice it: a strained firm attracts fewer prospects and makes existing clients quicker to walk; a thriving firm does the reverse. Partner promotions also require a credible FIRM score (40/45/50). Below 50, you can spend 1.5 hours pitching a turnaround for +10 FIRM, once every five days. Climbing to Senior Partner still costs a cash buy-in. Once your name is on the wall (ENDLESS), the firm is YOURS: manage payroll from the FIRM tab, fire the dead weight — but every firing invites a wrongful-termination lawsuit, and ex-employees never fully forget. If FIRM health collapses as Name Partner, so do you.<br/><br/>
          Keyboard: 1-4 picks an option, Space defers a file or advances the day summary, Esc closes panels.
        </div>
        <div className="opts"><button className="btn" onClick={closeInfo}>BACK TO BILLING</button></div>
      </div>
    </div>
  );
}
